name: date
version: 0.1.0
description: Complicated date parsing for Dart
homepage: https://github.com/logangorence/date
author: Logan Gorence <loganjohngorence@gmail.com>
environment:
  sdk: ">=1.5.0"
